backend:
  name: github
  repo: seankilleen/seankilleen.github.io
  branch: main # Branch to update
  site_domain: seankilleen.com # so we can get the github login redirected correctly
publish_mode: editorial_workflow
media_folder: "images/post-images" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blog" # Used in the UI, ie.: "New Post"
    folder: "_posts/" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Comments",
          name: "comments",
          widget: "boolean",
          default: true,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD HH:mm ZZ",
        }
      - label: "Header"
        name: "header"
        widget: object
        required: false
        fields:
          - {
              label: "Overlay Image",
              name: "overlay_image",
              widget: "string",
              required: false,
            }
          - {
              label: "Opacity",
              name: "overlay_filter",
              widget: "number",
              value_type: "float",
              min: 0.0,
              max: 1.0,
              step: 0.1,
              default: 0.5,
            }
          - { label: "Caption", name: "caption", widget: "string" }
    editor:
      preview: false
